# Iosevka 'Sharpie' variant: Iosevka with a few tweaks by Jeffrey Sharp
#
# SPDX-License-Identifier: CC0-1.0
#
# To the extent possible under law, Jeffrey Sharp has waived all copyright and
# related or neighbouring rights to this file.  This file is published from
# Canada.
#
# Fonts built by this file are derivatives of Iosevka and are licensed under
# the SIL Open Font License v1.1.  For more information, see:
# https://github.com/be5invis/Iosevka/blob/master/LICENSE.md
#
# References:
# - customizer: https://typeof.net/Iosevka/customizer
# - example:    https://github.com/be5invis/Iosevka/blob/master/private-build-plans.sample.toml
# - via npm:    npm run build -- ttf::iosevka-sharpie
# - via docker:
#   - *nix:     docker run --rm -it -e FONT_VERSION=16.3.6 -v $(pwd):/build avivace/iosevka-build ttf::iosevka-sharpie
#   - windows:  docker run --rm -it -e FONT_VERSION=16.3.6 -v ${PWD}:/build avivace/iosevka-build ttf::iosevka-sharpie
#
# Notes:
# - As of current writing, the FONT_VERSION environment variable is required to
#   make avivace/iosevka-build not crash out.
# - On SELinux-enabled distros like Fedora, use `-v $(pwd):/build:Z` to avoid a
#   permissions error.

[buildPlans.iosevka-sharpie]
family   = "Iosevka Sharpie"
spacing  = "term"
serifs   = "sans"
no-cv-ss = true

# -----------------------------------------------------------------------------
# Glyph Variants
#
# Use default Iosevka with just a few tweaks.
#

[buildPlans.iosevka-sharpie.variants.design]
# Letters
y              = "straight-turn"
lower-lambda   = "straight-turn"
cyrl-capital-u = "straight-turn"

# Punctuation
asterisk       = "hex-low"
brace          = "straight"

# -----------------------------------------------------------------------------
# Ligations
#
# Enable ligations for C-like languages, plus a few more.
#

[buildPlans.iosevka-sharpie.ligations]
inherits = "clike"
enables  = [
    "connected-hyphen-as-semi-dashed-line",     # -- => semi-dashed line
    "connected-underscore",                     # __ => solid line
    "ltgt-diamond",                             # <> => diamond
]

# -----------------------------------------------------------------------------
# Slopes
#
# Build the normal and italic slopes only.
#
# angle: angle in degrees                       ( 0.0 ..= 15.0  )
# shape: shape of the glyphs                    ( upright | italic | oblique )
# menu:  font name                              ( upright | italic | oblique )
# css:   webfont CSS 'font-style' property      ( normal  | italic | oblique )

[buildPlans.iosevka-sharpie.slopes.upright]
angle = 0
shape = "upright"
menu  = "upright"
css   = "normal"

[buildPlans.iosevka-sharpie.slopes.italic]
angle = 9.4
shape = "italic"
menu  = "italic"
css   = "italic"

# -----------------------------------------------------------------------------
# Widths
#
# Build the extended width only.
#
# shape: unit width in 1/1000 em                ( 434 ..= 664 )
# menu:  font name                              (   1 ..=   9 )
# css:   webfont CSS 'font-stretch' property    ( string      )
#

[buildPlans.iosevka-sharpie.widths.normal]
shape = 600
menu  = 5
css   = "normal"

# -----------------------------------------------------------------------------
# Weights
#
# Make thin to regular weights appear slightly heaver than normal.
#
# shape: shape of the glyphs                    ( 100 ..=  900 )
# menu:  font name                              (   0 ..  1000 )
# css:   webfont CSS 'font-weight' property     (   0 ..  1000 )
#

[buildPlans.iosevka-sharpie.weights.thin]
shape = 150
menu  = 100
css   = 100

[buildPlans.iosevka-sharpie.weights.extralight]
shape = 250
menu  = 200
css   = 200

[buildPlans.iosevka-sharpie.weights.light]
shape = 350
menu  = 300
css   = 300

[buildPlans.iosevka-sharpie.weights.regular]
shape = 450
menu  = 400
css   = 400

[buildPlans.iosevka-sharpie.weights.medium]
shape = 540
menu  = 500
css   = 500

[buildPlans.iosevka-sharpie.weights.semibold]
shape = 630
menu  = 600
css   = 600

[buildPlans.iosevka-sharpie.weights.bold]
shape = 720
menu  = 700
css   = 700

[buildPlans.iosevka-sharpie.weights.extrabold]
shape = 810
menu  = 800
css   = 800

[buildPlans.iosevka-sharpie.weights.heavy]
shape = 900
menu  = 900
css   = 900
