# Iosevka 'Sharpie' variant: Iosevka with a few tweaks by Jeffrey Sharp
# For Iosevka >= 28.0.0
#
# SPDX-License-Identifier: CC0-1.0
#
# To the extent possible under law, Jeffrey Sharp has waived all copyright and
# related or neighbouring rights to this file.  This file is published from
# Canada.
#
# Fonts built by this file are derivatives of Iosevka and are licensed under
# the SIL Open Font License v1.1.  For more information, see:
# https://github.com/be5invis/Iosevka/blob/main/LICENSE.md
#
# References:
# - reference:  https://github.com/be5invis/Iosevka/blob/main/doc/custom-build.md
# - ligations:  https://github.com/be5invis/Iosevka/blob/main/doc/language-specific-ligation-sets.md
# - example:    https://github.com/be5invis/Iosevka/blob/main/private-build-plans.sample.toml
# - customizer: https://typeof.net/Iosevka/customizer
# - via npm:    npm run build -- ttf::IosevkaSharpie
# - via docker:
#   - Build fontcc image: https://github.com/be5invis/Iosevka/blob/main/docker/README.md
#   - *nix:    docker run --rm -it -v $(pwd):/work fontcc ttf::IosevkaSharpie
#   - windows: docker run --rm -it -v ${PWD}:/work fontcc ttf::IosevkaSharpie
#     NOTE: As of 2024-03-09, autocrlf=false is required to avoid build failure.
#
# Notes:
# - On SELinux-enabled distros like Fedora, use `-v $(pwd):/work:Z` to avoid a
#   permissions error.
# - Add -e VERSION_TAG=vX.Y.Z to build a specific version.

[buildPlans.IosevkaSharpie]
family  = "Iosevka Sharpie"
spacing = "term"
serifs  = "sans"
noCvSs  = true

# -----------------------------------------------------------------------------
# Glyph Variants
#
# Use default Iosevka with just a few tweaks.
#

[buildPlans.IosevkaSharpie.variants.design]
# Letters
y              = "straight-turn-serifless"
cyrl-capital-u = "straight-turn-serifless"
lower-lambda   = "straight-turn"

# Digits
zero           = 'tall-slashed'

# Punctuation
asterisk       = "hex-low"
brace          = "straight"

# -----------------------------------------------------------------------------
# Ligations
#
# Enable ligations for C-like languages, plus a few more.
#

[buildPlans.IosevkaSharpie.ligations]
inherits = "julia"                              # clike plus arrows galore
disables = [
    "center-op-influence-dot"                   # centered dot in op chains
]
enables = [
    "minus-minus",                              # --   => semi-dashed line
    "underscore-underscopre",                   # __   => solid line
    "tilde-tilde",                              # ~~   => wavy line
    "ltgt-diamond",                             # <>   => diamond
    "html-comment",                             # <!-- => bang over arrow
]

# -----------------------------------------------------------------------------
# Slopes
#
# Build the normal and italic slopes only.
#
# angle: angle in degrees                       ( 0.0 ..= 15.0  )
# shape: shape of the glyphs                    ( upright | italic | oblique )
# menu:  font name                              ( upright | italic | oblique )
# css:   webfont CSS 'font-style' property      ( normal  | italic | oblique )

[buildPlans.IosevkaSharpie.slopes.upright]
angle = 0
shape = "upright"
menu  = "upright"
css   = "normal"

[buildPlans.IosevkaSharpie.slopes.italic]
angle = 9.4
shape = "italic"
menu  = "italic"
css   = "italic"

# -----------------------------------------------------------------------------
# Widths
#
# Build the extended width only.
#
# shape: unit width in 1/1000 em                ( 434 ..= 664 )
# menu:  font name                              (   1 ..=   9 )
# css:   webfont CSS 'font-stretch' property    ( string      )
#

[buildPlans.IosevkaSharpie.widths.normal]
shape = 600
menu  = 5
css   = "normal"

# -----------------------------------------------------------------------------
# Weights
#
# Make thin to regular weights appear slightly heaver than normal.
#
# shape: shape of the glyphs                    ( 100 ..=  900 )
# menu:  font name                              (   0 ..  1000 )
# css:   webfont CSS 'font-weight' property     (   0 ..  1000 )
#

[buildPlans.IosevkaSharpie.weights.thin]
shape = 150
menu  = 100
css   = 100

[buildPlans.IosevkaSharpie.weights.extralight]
shape = 250
menu  = 200
css   = 200

[buildPlans.IosevkaSharpie.weights.light]
shape = 350
menu  = 300
css   = 300

[buildPlans.IosevkaSharpie.weights.regular]
shape = 450
menu  = 400
css   = 400

[buildPlans.IosevkaSharpie.weights.medium]
shape = 540
menu  = 500
css   = 500

[buildPlans.IosevkaSharpie.weights.semibold]
shape = 630
menu  = 600
css   = 600

[buildPlans.IosevkaSharpie.weights.bold]
shape = 720
menu  = 700
css   = 700

[buildPlans.IosevkaSharpie.weights.extrabold]
shape = 810
menu  = 800
css   = 800

[buildPlans.IosevkaSharpie.weights.heavy]
shape = 900
menu  = 900
css   = 900
