#Requires -Version 7
$ErrorActionPreference = "Stop"
Set-StrictMode -Version 3.0

if ($PSEdition -ne "Desktop" -and -not $IsWindows) {
    throw "This command supports Windows only."
}

Add-Type -AssemblyName PresentationCore

$Path = Get-Item $PSScriptRoot\..\dist\IosevkaSharpie\TTF\*.ttf `
    | Select-Object -First 1 `
    | ForEach-Object FullName

$Version = [System.Windows.Media.GlyphTypeface]::new($Path).VersionStrings.Values `
    -replace '^.*?([0-9]+\.[0-9]+\.[0-9]+).*$', '$1' `
    | Select-Object -First 1

Set-Content $PSScriptRoot\Version.props -Force @"
<!-- Generated by Get-IosevkaSharpieVersion.ps1 -->
<Project>
  <PropertyGroup>
    <Version Condition="'`$(Version)' == ''">$Version</Version>
  </PropertyGroup>
</Project>
"@

Write-Host "Wrote version $Version to Version.props file."
